function rois = all_rois()

% VIS
rois = {'VISp1','VISp2/3','VISp4', 'VISp5','VISp6', 'LGd', 'LP', ...
        'VISa1', 'VISa2/3', 'VISa4', 'VISa5', 'VISa6a', 'VISa6b', ...
        'VISrl1', 'VISrl2/3', 'VISrl4', 'VISrl5', 'VISrl6a', 'VISrl6b', ...
        'VISam1', 'VISam2/3', 'VISam4', 'VISam5', 'VISam6a', 'VISam6b', ...
        'VISpm1', 'VISpm2/3', 'VISpm4', 'VISpm5', 'VISpm6a', 'VISpm6b', 'APN', ...
        'PF', 'PO', 'POL', 'PVT', 'TH', 'MD', ...
        'RSPagl1', 'RSPagl2/3', 'RSPagl5', 'RSPagl6a','RSPagl6b', ...
        'RSPd1', 'RSPd2/3', 'RSPd5', 'RSPd6a','RSPd6b', ...
        'RSPv1', 'RSPv2/3', 'RSPv5', 'RSPv6a','RSPv6b', ...
        'CP',  'MOs1', 'MOs2/3', 'MOs5', 'MOs6b', 'STR', ...
        'ACAd5', 'ACAd6a', 'ACAv6a', 'ACAv6b',  ...
        'ILA1', 'ILA2/3', 'ILA5',...
        'PL2/3', 'PL5', 'PL6a', 'PL6b'}; 
            
end